spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeaway #?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off # 设置springboot启动图标不显示
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志到控制台，会影响性能
  global-config:
    banner: off # 设置MyBatisPlus启动图标不显示
    db-config:
      id-type: assign_id #设置主键增加策略
takeaway:
  path: D:\img\